import type { Metadata } from "next";
import "./globals.css";
import ThemeProvider from "@/Provider/ThemeProvider";
import WindowProvider from "@/Provider/WindowWrapper";
import ReactQueryProvider from "@/Provider/ReactQueryProvider";
import ToastProvider from "@/Provider/ToastProvider";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import Chat from "@/components/chat";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>
          <WindowProvider>
            <NuqsAdapter>
              <ThemeProvider>
                <ToastProvider>
                  {children}
                  <Chat />
                </ToastProvider>
              </ThemeProvider>
            </NuqsAdapter>
          </WindowProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
